Merge experiments into main
weecology/EvergladesSpeciesModel pull request #31
Opened 2022-09-15 18:14 UTC by bw4sz

This PR brings my work into the main branch.
# Summary
* Remove loss weighting to improve empty frame stability
* Add photoshop annotations for weak training from Lindsey's data
* Scripts to generate weak annotations for mining
* A few tests to ensure empty annotations are working as intended
* An update to the empty frame csv
* Add an anhinga class for training purposes to reduce confusion

2022-09-15 18:14 UTC, bw4sz commented
Note that this is supposed to be squashed before merge.

2022-09-20 15:30 UTC, ethanwhite requested changes
Overall this looks great. I have a handful of detailed suggestions/questions.

My one bigger question is it looks like you've pulled a bunch of stuff out into `evaluate_only.py`, which makes sense, but I don't see that module getting used anywhere. So right now it seems like it's unlinked code for anyone but you. Am I missing something?

2022-09-20 15:30 UTC, ethanwhite commented on experiment.sh
> +source activate DeepTreeAttention
This should be the environment created by the environment.yml in the repo, which currently creates an environment named ESM. If the environment needs updating it should be done by updating the environment.yml file to include the necessary dependencies.

2022-09-20 15:30 UTC, ethanwhite commented on create_empty_frame_csv.py
> +#images = [os.path.basename(x) for x in images]
If we don't need this commented out line it should be dropped. If it's used periodically for some purpose that should be documented with a comment.

2022-09-20 15:30 UTC, ethanwhite commented on evaluate_only.py
> +        model.config["score_thresh"] = 0.01
Add a brief commend between Lines 144 and 145 explaining the threshold switching.

2022-09-20 15:30 UTC, ethanwhite commented on everglades_species.py
> +    #add in weak annotations
Change to `#add in weak empty frame annotations`

2022-09-20 15:30 UTC, ethanwhite commented on everglades_species.py
> +    #im_callback = images_callback(csv_file=model.config["validation"]["csv_file"], root_dir=model.config["validation"]["root_dir"], savedir=model_savedir, n=20)
Add a comment above this explaining when to uncomment it.

2022-09-20 15:30 UTC, ethanwhite commented on everglades_species.py
> +            model.label_dict.update({'Bird Not Detected': 7})
Can you explain this change to me so I understand it? We have 6 species, which I believe were encoded 0, 1, 2, 3, 4, 5, hence the addition with the 6. Is there a change to keep 0 for background somewhere else or something different?

2022-09-20 16:30 UTC, bw4sz commented on everglades_species.py
> +            model.label_dict.update({'Bird Not Detected': 7})
Added Anhinga.

2022-09-20 16:30 UTC, bw4sz commented on everglades_species.py
> +            model.label_dict.update({'Bird Not Detected': 7})
Just for model training, no test, kinda like a distraction class.

2022-09-20 17:51 UTC, ethanwhite commented on everglades_species.py
> +            model.label_dict.update({'Bird Not Detected': 7})
This is a nice example of a case where compartmentalized commits can really help with communication. A single commit with this change that indicates that it is to add Anhinga would make it easy for someone who was confused to quickly understand the source of the `7` using blame (and make it easy for someone reviewing the PR to understand why the change was made).

2022-09-20 18:11 UTC, bw4sz commented on empty_frames_utilities.py
> +        metric_name = "BirdRecall_at_0.3"
No, the naming here is the recall value at the desired threshold, I will rename.

2022-09-20 18:17 UTC, bw4sz commented on everglades_species.py
> +    comet_logger = CometLogger(project_name="everglades-species", workspace="bw4sz", experiment_name=experiment_name)
In terms of separate users contributing the one dashboard, we can't do that unless we change comet tiers, or we get a joint user account. Good(ish) news is that the code can stay as /weecology/ so that it defaults to your account. My .comet.config 

```
(DeepTreeAttention) [b.weinstein@c0906a-s35 EvergladesSpeciesModel]$ cat ~/.comet.config
[comet]
api_key=###########
```
takes precedence. So it will get place in /bw4sz/

2022-09-20 18:17 UTC, bw4sz commented on experiment.sh
> +source activate DeepTreeAttention
Building now, very slow.

2022-09-20 22:06 UTC, bw4sz commented on experiment.sh
> +source activate DeepTreeAttention
Runs clean for me. Changed name back to ESM.

2022-09-21 03:09 UTC, bw4sz commented
I believe all issues have been resolved.

2022-09-21 12:15 UTC, ethanwhite requested changes
Just a couple of last little things. If I misunderstood your last comment on Slack then feel free to ignore the bw4sz -> weecology comments.

2022-09-21 12:15 UTC, ethanwhite commented on experiment.sh
> +source activate DeepTreeAttention
I'm still seeing the change from `ESM` to `DeepTreeAttention` here

2022-09-21 12:15 UTC, ethanwhite commented on everglades_species.py
> +    comet_logger = CometLogger(project_name="everglades-species", workspace="bw4sz", experiment_name=experiment_name)
Are we putting this back to `weecology` based on the discussion in Slack?

2022-09-21 12:15 UTC, ethanwhite commented on evaluate.py
> +        comet_logger = CometLogger(project_name="everglades-species", workspace="bw4sz", experiment_name=experiment_name)
Are we changing this to `weecology` based on the discussion in Slack?

2022-09-21 12:15 UTC, ethanwhite commented on everglades_species.py
> +           'Great Blue Heron', 'Wood Stork', 'Snowy Egret',"Anhinga"])]
Since there are a couple of other things to cleanup anyway - white space after the comma before Anhinga and single quotes for consistency with the rest of the list.

2022-09-21 16:34 UTC, bw4sz commented on experiment.sh
> +source activate DeepTreeAttention
We must be offset, pushing, I've got ESM here.

2022-09-21 16:35 UTC, bw4sz commented on experiment.sh
> +source activate DeepTreeAttention
I'm up to date, hard refresh?

2022-09-21 16:37 UTC, bw4sz commented on experiment.sh
> +source activate DeepTreeAttention
I think it fixed itself. 
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1208492/191561755-d140faf5-9ac0-4f1f-bfeb-ecf3ee18af65.png">

2022-09-21 16:58 UTC, ethanwhite commented on experiment.sh
> +source activate DeepTreeAttention
:+1: looks good now

2022-09-21 18:51 UTC, merged